# Generated by Django 5.1.15 on 2026-03-08 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customuser_managers_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="completed",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Positive for deposit/win/bonus, negative for withdraw/bet",
                max_digits=12,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Balance After Transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional note about the transaction",
                max_length=255,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("bet", "Bet"),
                    ("win", "Win"),
                    ("bonus", "Bonus"),
                    ("referral", "Referral Bonus"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
