# Generated by Django 5.1.15 on 2026-03-08 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rechargepromotion_giftcode_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcode",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="giftcode",
            name="max_uses",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="giftcode",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="giftcode",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_gift_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rechargepromotion",
            name="bonus_percent",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="rechargepromotion",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
