# Generated by Django 5.1.15 on 2026-03-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_giftcode_expires_at_giftcode_max_uses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("level", models.PositiveIntegerField(unique=True)),
                (
                    "direct_commission_percent",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "team_commission_percent",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("min_referrals_for_level", models.PositiveIntegerField(default=0)),
                (
                    "min_deposit_for_level",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="UserAgencyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_direct_referrals", models.PositiveIntegerField(default=0)),
                ("total_team_referrals", models.PositiveIntegerField(default=0)),
                (
                    "yesterday_commission",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                (
                    "current_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agencylevel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
