# Generated by Django 5.1.15 on 2026-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_agencylevel_useragencyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
