# Generated by Django 5.1.15 on 2026-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depositrequest",
            name="screenshot",
        ),
        migrations.AddField(
            model_name="depositrequest",
            name="screenshot_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
