# Generated by Django 5.1.15 on 2026-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_depositrequest_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawrequest",
            name="screenshot_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
